# Generated by Django 4.1.2 on 2022-11-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_planet_film_film_planets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='open_text',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
