# Generated by Django 4.1.2 on 2022-11-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_film_open_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(blank=True, default='', max_length=150, null=True),
        ),
    ]
